// source: common.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var duration_pb = require('./duration_pb.js');
goog.object.extend(proto, duration_pb);
var timestamp_pb = require('./timestamp_pb.js');
goog.object.extend(proto, timestamp_pb);
goog.exportSymbol('proto.resultstoresearch.v1.Dependency', null, global);
goog.exportSymbol(
    'proto.resultstoresearch.v1.Dependency.ResourceCase',
    null,
    global
);
goog.exportSymbol('proto.resultstoresearch.v1.Language', null, global);
goog.exportSymbol('proto.resultstoresearch.v1.Property', null, global);
goog.exportSymbol('proto.resultstoresearch.v1.Status', null, global);
goog.exportSymbol('proto.resultstoresearch.v1.StatusAttributes', null, global);
goog.exportSymbol('proto.resultstoresearch.v1.Timing', null, global);
goog.exportSymbol('proto.resultstoresearch.v1.UploadStatus', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resultstoresearch.v1.StatusAttributes = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resultstoresearch.v1.StatusAttributes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.resultstoresearch.v1.StatusAttributes.displayName =
        'proto.resultstoresearch.v1.StatusAttributes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resultstoresearch.v1.Property = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resultstoresearch.v1.Property, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.resultstoresearch.v1.Property.displayName =
        'proto.resultstoresearch.v1.Property';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resultstoresearch.v1.Timing = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resultstoresearch.v1.Timing, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.resultstoresearch.v1.Timing.displayName =
        'proto.resultstoresearch.v1.Timing';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resultstoresearch.v1.Dependency = function (opt_data) {
    jspb.Message.initialize(
        this,
        opt_data,
        0,
        -1,
        null,
        proto.resultstoresearch.v1.Dependency.oneofGroups_
    );
};
goog.inherits(proto.resultstoresearch.v1.Dependency, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.resultstoresearch.v1.Dependency.displayName =
        'proto.resultstoresearch.v1.Dependency';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.resultstoresearch.v1.StatusAttributes.prototype.toObject = function (
        opt_includeInstance
    ) {
        return proto.resultstoresearch.v1.StatusAttributes.toObject(
            opt_includeInstance,
            this
        );
    };

    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.resultstoresearch.v1.StatusAttributes} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.resultstoresearch.v1.StatusAttributes.toObject = function (
        includeInstance,
        msg
    ) {
        var f,
            obj = {
                status: jspb.Message.getFieldWithDefault(msg, 1, 0),
                description: jspb.Message.getFieldWithDefault(msg, 2, ''),
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resultstoresearch.v1.StatusAttributes}
 */
proto.resultstoresearch.v1.StatusAttributes.deserializeBinary = function (
    bytes
) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.resultstoresearch.v1.StatusAttributes();
    return proto.resultstoresearch.v1.StatusAttributes.deserializeBinaryFromReader(
        msg,
        reader
    );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resultstoresearch.v1.StatusAttributes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resultstoresearch.v1.StatusAttributes}
 */
proto.resultstoresearch.v1.StatusAttributes.deserializeBinaryFromReader = function (
    msg,
    reader
) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {!proto.resultstoresearch.v1.Status} */ (reader.readEnum());
                msg.setStatus(value);
                break;
            case 2:
                var value = /** @type {string} */ (reader.readString());
                msg.setDescription(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resultstoresearch.v1.StatusAttributes.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    proto.resultstoresearch.v1.StatusAttributes.serializeBinaryToWriter(
        this,
        writer
    );
    return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resultstoresearch.v1.StatusAttributes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resultstoresearch.v1.StatusAttributes.serializeBinaryToWriter = function (
    message,
    writer
) {
    var f = undefined;
    f = message.getStatus();
    if (f !== 0.0) {
        writer.writeEnum(1, f);
    }
    f = message.getDescription();
    if (f.length > 0) {
        writer.writeString(2, f);
    }
};

/**
 * optional Status status = 1;
 * @return {!proto.resultstoresearch.v1.Status}
 */
proto.resultstoresearch.v1.StatusAttributes.prototype.getStatus = function () {
    return /** @type {!proto.resultstoresearch.v1.Status} */ (jspb.Message.getFieldWithDefault(
        this,
        1,
        0
    ));
};

/**
 * @param {!proto.resultstoresearch.v1.Status} value
 * @return {!proto.resultstoresearch.v1.StatusAttributes} returns this
 */
proto.resultstoresearch.v1.StatusAttributes.prototype.setStatus = function (
    value
) {
    return jspb.Message.setProto3EnumField(this, 1, value);
};

/**
 * optional string description = 2;
 * @return {string}
 */
proto.resultstoresearch.v1.StatusAttributes.prototype.getDescription = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(
        this,
        2,
        ''
    ));
};

/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.StatusAttributes} returns this
 */
proto.resultstoresearch.v1.StatusAttributes.prototype.setDescription = function (
    value
) {
    return jspb.Message.setProto3StringField(this, 2, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.resultstoresearch.v1.Property.prototype.toObject = function (
        opt_includeInstance
    ) {
        return proto.resultstoresearch.v1.Property.toObject(
            opt_includeInstance,
            this
        );
    };

    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.resultstoresearch.v1.Property} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.resultstoresearch.v1.Property.toObject = function (
        includeInstance,
        msg
    ) {
        var f,
            obj = {
                key: jspb.Message.getFieldWithDefault(msg, 1, ''),
                value: jspb.Message.getFieldWithDefault(msg, 2, ''),
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resultstoresearch.v1.Property}
 */
proto.resultstoresearch.v1.Property.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.resultstoresearch.v1.Property();
    return proto.resultstoresearch.v1.Property.deserializeBinaryFromReader(
        msg,
        reader
    );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resultstoresearch.v1.Property} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resultstoresearch.v1.Property}
 */
proto.resultstoresearch.v1.Property.deserializeBinaryFromReader = function (
    msg,
    reader
) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {string} */ (reader.readString());
                msg.setKey(value);
                break;
            case 2:
                var value = /** @type {string} */ (reader.readString());
                msg.setValue(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resultstoresearch.v1.Property.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    proto.resultstoresearch.v1.Property.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resultstoresearch.v1.Property} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resultstoresearch.v1.Property.serializeBinaryToWriter = function (
    message,
    writer
) {
    var f = undefined;
    f = message.getKey();
    if (f.length > 0) {
        writer.writeString(1, f);
    }
    f = message.getValue();
    if (f.length > 0) {
        writer.writeString(2, f);
    }
};

/**
 * optional string key = 1;
 * @return {string}
 */
proto.resultstoresearch.v1.Property.prototype.getKey = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(
        this,
        1,
        ''
    ));
};

/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.Property} returns this
 */
proto.resultstoresearch.v1.Property.prototype.setKey = function (value) {
    return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string value = 2;
 * @return {string}
 */
proto.resultstoresearch.v1.Property.prototype.getValue = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(
        this,
        2,
        ''
    ));
};

/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.Property} returns this
 */
proto.resultstoresearch.v1.Property.prototype.setValue = function (value) {
    return jspb.Message.setProto3StringField(this, 2, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.resultstoresearch.v1.Timing.prototype.toObject = function (
        opt_includeInstance
    ) {
        return proto.resultstoresearch.v1.Timing.toObject(
            opt_includeInstance,
            this
        );
    };

    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.resultstoresearch.v1.Timing} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.resultstoresearch.v1.Timing.toObject = function (
        includeInstance,
        msg
    ) {
        var f,
            obj = {
                startTime:
                    (f = msg.getStartTime()) &&
                    timestamp_pb.Timestamp.toObject(includeInstance, f),
                duration:
                    (f = msg.getDuration()) &&
                    duration_pb.Duration.toObject(includeInstance, f),
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resultstoresearch.v1.Timing}
 */
proto.resultstoresearch.v1.Timing.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.resultstoresearch.v1.Timing();
    return proto.resultstoresearch.v1.Timing.deserializeBinaryFromReader(
        msg,
        reader
    );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resultstoresearch.v1.Timing} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resultstoresearch.v1.Timing}
 */
proto.resultstoresearch.v1.Timing.deserializeBinaryFromReader = function (
    msg,
    reader
) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = new timestamp_pb.Timestamp();
                reader.readMessage(
                    value,
                    timestamp_pb.Timestamp.deserializeBinaryFromReader
                );
                msg.setStartTime(value);
                break;
            case 2:
                var value = new duration_pb.Duration();
                reader.readMessage(
                    value,
                    duration_pb.Duration.deserializeBinaryFromReader
                );
                msg.setDuration(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resultstoresearch.v1.Timing.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    proto.resultstoresearch.v1.Timing.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resultstoresearch.v1.Timing} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resultstoresearch.v1.Timing.serializeBinaryToWriter = function (
    message,
    writer
) {
    var f = undefined;
    f = message.getStartTime();
    if (f != null) {
        writer.writeMessage(
            1,
            f,
            timestamp_pb.Timestamp.serializeBinaryToWriter
        );
    }
    f = message.getDuration();
    if (f != null) {
        writer.writeMessage(2, f, duration_pb.Duration.serializeBinaryToWriter);
    }
};

/**
 * optional Timestamp start_time = 1;
 * @return {?proto.resultstoresearch.v1.Timestamp}
 */
proto.resultstoresearch.v1.Timing.prototype.getStartTime = function () {
    return /** @type{?proto.resultstoresearch.v1.Timestamp} */ (jspb.Message.getWrapperField(
        this,
        timestamp_pb.Timestamp,
        1
    ));
};

/**
 * @param {?proto.resultstoresearch.v1.Timestamp|undefined} value
 * @return {!proto.resultstoresearch.v1.Timing} returns this
 */
proto.resultstoresearch.v1.Timing.prototype.setStartTime = function (value) {
    return jspb.Message.setWrapperField(this, 1, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.resultstoresearch.v1.Timing} returns this
 */
proto.resultstoresearch.v1.Timing.prototype.clearStartTime = function () {
    return this.setStartTime(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resultstoresearch.v1.Timing.prototype.hasStartTime = function () {
    return jspb.Message.getField(this, 1) != null;
};

/**
 * optional Duration duration = 2;
 * @return {?proto.resultstoresearch.v1.Duration}
 */
proto.resultstoresearch.v1.Timing.prototype.getDuration = function () {
    return /** @type{?proto.resultstoresearch.v1.Duration} */ (jspb.Message.getWrapperField(
        this,
        duration_pb.Duration,
        2
    ));
};

/**
 * @param {?proto.resultstoresearch.v1.Duration|undefined} value
 * @return {!proto.resultstoresearch.v1.Timing} returns this
 */
proto.resultstoresearch.v1.Timing.prototype.setDuration = function (value) {
    return jspb.Message.setWrapperField(this, 2, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.resultstoresearch.v1.Timing} returns this
 */
proto.resultstoresearch.v1.Timing.prototype.clearDuration = function () {
    return this.setDuration(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resultstoresearch.v1.Timing.prototype.hasDuration = function () {
    return jspb.Message.getField(this, 2) != null;
};

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.resultstoresearch.v1.Dependency.oneofGroups_ = [[1, 2, 3]];

/**
 * @enum {number}
 */
proto.resultstoresearch.v1.Dependency.ResourceCase = {
    RESOURCE_NOT_SET: 0,
    TARGET: 1,
    CONFIGURED_TARGET: 2,
    ACTION: 3,
};

/**
 * @return {proto.resultstoresearch.v1.Dependency.ResourceCase}
 */
proto.resultstoresearch.v1.Dependency.prototype.getResourceCase = function () {
    return /** @type {proto.resultstoresearch.v1.Dependency.ResourceCase} */ (jspb.Message.computeOneofCase(
        this,
        proto.resultstoresearch.v1.Dependency.oneofGroups_[0]
    ));
};

if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.resultstoresearch.v1.Dependency.prototype.toObject = function (
        opt_includeInstance
    ) {
        return proto.resultstoresearch.v1.Dependency.toObject(
            opt_includeInstance,
            this
        );
    };

    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.resultstoresearch.v1.Dependency} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.resultstoresearch.v1.Dependency.toObject = function (
        includeInstance,
        msg
    ) {
        var f,
            obj = {
                target: jspb.Message.getFieldWithDefault(msg, 1, ''),
                configuredTarget: jspb.Message.getFieldWithDefault(msg, 2, ''),
                action: jspb.Message.getFieldWithDefault(msg, 3, ''),
                label: jspb.Message.getFieldWithDefault(msg, 4, ''),
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resultstoresearch.v1.Dependency}
 */
proto.resultstoresearch.v1.Dependency.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.resultstoresearch.v1.Dependency();
    return proto.resultstoresearch.v1.Dependency.deserializeBinaryFromReader(
        msg,
        reader
    );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resultstoresearch.v1.Dependency} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resultstoresearch.v1.Dependency}
 */
proto.resultstoresearch.v1.Dependency.deserializeBinaryFromReader = function (
    msg,
    reader
) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {string} */ (reader.readString());
                msg.setTarget(value);
                break;
            case 2:
                var value = /** @type {string} */ (reader.readString());
                msg.setConfiguredTarget(value);
                break;
            case 3:
                var value = /** @type {string} */ (reader.readString());
                msg.setAction(value);
                break;
            case 4:
                var value = /** @type {string} */ (reader.readString());
                msg.setLabel(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resultstoresearch.v1.Dependency.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    proto.resultstoresearch.v1.Dependency.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resultstoresearch.v1.Dependency} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resultstoresearch.v1.Dependency.serializeBinaryToWriter = function (
    message,
    writer
) {
    var f = undefined;
    f = /** @type {string} */ (jspb.Message.getField(message, 1));
    if (f != null) {
        writer.writeString(1, f);
    }
    f = /** @type {string} */ (jspb.Message.getField(message, 2));
    if (f != null) {
        writer.writeString(2, f);
    }
    f = /** @type {string} */ (jspb.Message.getField(message, 3));
    if (f != null) {
        writer.writeString(3, f);
    }
    f = message.getLabel();
    if (f.length > 0) {
        writer.writeString(4, f);
    }
};

/**
 * optional string target = 1;
 * @return {string}
 */
proto.resultstoresearch.v1.Dependency.prototype.getTarget = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(
        this,
        1,
        ''
    ));
};

/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.Dependency} returns this
 */
proto.resultstoresearch.v1.Dependency.prototype.setTarget = function (value) {
    return jspb.Message.setOneofField(
        this,
        1,
        proto.resultstoresearch.v1.Dependency.oneofGroups_[0],
        value
    );
};

/**
 * Clears the field making it undefined.
 * @return {!proto.resultstoresearch.v1.Dependency} returns this
 */
proto.resultstoresearch.v1.Dependency.prototype.clearTarget = function () {
    return jspb.Message.setOneofField(
        this,
        1,
        proto.resultstoresearch.v1.Dependency.oneofGroups_[0],
        undefined
    );
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resultstoresearch.v1.Dependency.prototype.hasTarget = function () {
    return jspb.Message.getField(this, 1) != null;
};

/**
 * optional string configured_target = 2;
 * @return {string}
 */
proto.resultstoresearch.v1.Dependency.prototype.getConfiguredTarget = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(
        this,
        2,
        ''
    ));
};

/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.Dependency} returns this
 */
proto.resultstoresearch.v1.Dependency.prototype.setConfiguredTarget = function (
    value
) {
    return jspb.Message.setOneofField(
        this,
        2,
        proto.resultstoresearch.v1.Dependency.oneofGroups_[0],
        value
    );
};

/**
 * Clears the field making it undefined.
 * @return {!proto.resultstoresearch.v1.Dependency} returns this
 */
proto.resultstoresearch.v1.Dependency.prototype.clearConfiguredTarget = function () {
    return jspb.Message.setOneofField(
        this,
        2,
        proto.resultstoresearch.v1.Dependency.oneofGroups_[0],
        undefined
    );
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resultstoresearch.v1.Dependency.prototype.hasConfiguredTarget = function () {
    return jspb.Message.getField(this, 2) != null;
};

/**
 * optional string action = 3;
 * @return {string}
 */
proto.resultstoresearch.v1.Dependency.prototype.getAction = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(
        this,
        3,
        ''
    ));
};

/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.Dependency} returns this
 */
proto.resultstoresearch.v1.Dependency.prototype.setAction = function (value) {
    return jspb.Message.setOneofField(
        this,
        3,
        proto.resultstoresearch.v1.Dependency.oneofGroups_[0],
        value
    );
};

/**
 * Clears the field making it undefined.
 * @return {!proto.resultstoresearch.v1.Dependency} returns this
 */
proto.resultstoresearch.v1.Dependency.prototype.clearAction = function () {
    return jspb.Message.setOneofField(
        this,
        3,
        proto.resultstoresearch.v1.Dependency.oneofGroups_[0],
        undefined
    );
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resultstoresearch.v1.Dependency.prototype.hasAction = function () {
    return jspb.Message.getField(this, 3) != null;
};

/**
 * optional string label = 4;
 * @return {string}
 */
proto.resultstoresearch.v1.Dependency.prototype.getLabel = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(
        this,
        4,
        ''
    ));
};

/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.Dependency} returns this
 */
proto.resultstoresearch.v1.Dependency.prototype.setLabel = function (value) {
    return jspb.Message.setProto3StringField(this, 4, value);
};

/**
 * @enum {number}
 */
proto.resultstoresearch.v1.Language = {
    LANGUAGE_UNSPECIFIED: 0,
    NONE: 1,
    ANDROID: 2,
    AS: 3,
    CC: 4,
    CSS: 5,
    DART: 6,
    GO: 7,
    GWT: 8,
    HASKELL: 9,
    JAVA: 10,
    JS: 11,
    LISP: 12,
    OBJC: 13,
    PY: 14,
    SH: 15,
    SWIFT: 16,
    TS: 18,
    WEB: 19,
    SCALA: 20,
    PROTO: 21,
    XML: 22,
};

/**
 * @enum {number}
 */
proto.resultstoresearch.v1.Status = {
    STATUS_UNSPECIFIED: 0,
    BUILDING: 1,
    BUILT: 2,
    FAILED_TO_BUILD: 3,
    TESTING: 4,
    PASSED: 5,
    FAILED: 6,
    TIMED_OUT: 7,
    CANCELLED: 8,
    TOOL_FAILED: 9,
    INCOMPLETE: 10,
    FLAKY: 11,
    UNKNOWN: 12,
    SKIPPED: 13,
};

/**
 * @enum {number}
 */
proto.resultstoresearch.v1.UploadStatus = {
    UPLOAD_STATUS_UNSPECIFIED: 0,
    UPLOADING: 1,
    POST_PROCESSING: 2,
    IMMUTABLE: 3,
};

goog.object.extend(exports, proto.resultstoresearch.v1);
