// source: common.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */

goog.provide('proto.resultstoresearch.v1.Dependency');
goog.provide('proto.resultstoresearch.v1.Dependency.ResourceCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resultstoresearch.v1.Dependency = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.resultstoresearch.v1.Dependency.oneofGroups_);
};
goog.inherits(proto.resultstoresearch.v1.Dependency, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.resultstoresearch.v1.Dependency.displayName = 'proto.resultstoresearch.v1.Dependency';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.resultstoresearch.v1.Dependency.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.resultstoresearch.v1.Dependency.ResourceCase = {
  RESOURCE_NOT_SET: 0,
  TARGET: 1,
  CONFIGURED_TARGET: 2,
  ACTION: 3
};

/**
 * @return {proto.resultstoresearch.v1.Dependency.ResourceCase}
 */
proto.resultstoresearch.v1.Dependency.prototype.getResourceCase = function() {
  return /** @type {proto.resultstoresearch.v1.Dependency.ResourceCase} */(jspb.Message.computeOneofCase(this, proto.resultstoresearch.v1.Dependency.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resultstoresearch.v1.Dependency.prototype.toObject = function(opt_includeInstance) {
  return proto.resultstoresearch.v1.Dependency.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resultstoresearch.v1.Dependency} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resultstoresearch.v1.Dependency.toObject = function(includeInstance, msg) {
  var f, obj = {
    target: jspb.Message.getFieldWithDefault(msg, 1, ""),
    configuredTarget: jspb.Message.getFieldWithDefault(msg, 2, ""),
    action: jspb.Message.getFieldWithDefault(msg, 3, ""),
    label: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resultstoresearch.v1.Dependency}
 */
proto.resultstoresearch.v1.Dependency.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resultstoresearch.v1.Dependency;
  return proto.resultstoresearch.v1.Dependency.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resultstoresearch.v1.Dependency} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resultstoresearch.v1.Dependency}
 */
proto.resultstoresearch.v1.Dependency.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTarget(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setConfiguredTarget(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAction(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setLabel(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resultstoresearch.v1.Dependency.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.resultstoresearch.v1.Dependency.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resultstoresearch.v1.Dependency} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resultstoresearch.v1.Dependency.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLabel();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string target = 1;
 * @return {string}
 */
proto.resultstoresearch.v1.Dependency.prototype.getTarget = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.Dependency} returns this
 */
proto.resultstoresearch.v1.Dependency.prototype.setTarget = function(value) {
  return jspb.Message.setOneofField(this, 1, proto.resultstoresearch.v1.Dependency.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.resultstoresearch.v1.Dependency} returns this
 */
proto.resultstoresearch.v1.Dependency.prototype.clearTarget = function() {
  return jspb.Message.setOneofField(this, 1, proto.resultstoresearch.v1.Dependency.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resultstoresearch.v1.Dependency.prototype.hasTarget = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string configured_target = 2;
 * @return {string}
 */
proto.resultstoresearch.v1.Dependency.prototype.getConfiguredTarget = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.Dependency} returns this
 */
proto.resultstoresearch.v1.Dependency.prototype.setConfiguredTarget = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.resultstoresearch.v1.Dependency.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.resultstoresearch.v1.Dependency} returns this
 */
proto.resultstoresearch.v1.Dependency.prototype.clearConfiguredTarget = function() {
  return jspb.Message.setOneofField(this, 2, proto.resultstoresearch.v1.Dependency.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resultstoresearch.v1.Dependency.prototype.hasConfiguredTarget = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string action = 3;
 * @return {string}
 */
proto.resultstoresearch.v1.Dependency.prototype.getAction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.Dependency} returns this
 */
proto.resultstoresearch.v1.Dependency.prototype.setAction = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.resultstoresearch.v1.Dependency.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.resultstoresearch.v1.Dependency} returns this
 */
proto.resultstoresearch.v1.Dependency.prototype.clearAction = function() {
  return jspb.Message.setOneofField(this, 3, proto.resultstoresearch.v1.Dependency.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resultstoresearch.v1.Dependency.prototype.hasAction = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string label = 4;
 * @return {string}
 */
proto.resultstoresearch.v1.Dependency.prototype.getLabel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.Dependency} returns this
 */
proto.resultstoresearch.v1.Dependency.prototype.setLabel = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


