// source: coverage.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */

goog.provide('proto.resultstoresearch.v1.FileCoverage');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.resultstoresearch.v1.BranchCoverage');
goog.require('proto.resultstoresearch.v1.LineCoverage');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resultstoresearch.v1.FileCoverage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resultstoresearch.v1.FileCoverage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.resultstoresearch.v1.FileCoverage.displayName = 'proto.resultstoresearch.v1.FileCoverage';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resultstoresearch.v1.FileCoverage.prototype.toObject = function(opt_includeInstance) {
  return proto.resultstoresearch.v1.FileCoverage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resultstoresearch.v1.FileCoverage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resultstoresearch.v1.FileCoverage.toObject = function(includeInstance, msg) {
  var f, obj = {
    path: jspb.Message.getFieldWithDefault(msg, 1, ""),
    lineCoverage: (f = msg.getLineCoverage()) && proto.resultstoresearch.v1.LineCoverage.toObject(includeInstance, f),
    branchCoverage: (f = msg.getBranchCoverage()) && proto.resultstoresearch.v1.BranchCoverage.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resultstoresearch.v1.FileCoverage}
 */
proto.resultstoresearch.v1.FileCoverage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resultstoresearch.v1.FileCoverage;
  return proto.resultstoresearch.v1.FileCoverage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resultstoresearch.v1.FileCoverage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resultstoresearch.v1.FileCoverage}
 */
proto.resultstoresearch.v1.FileCoverage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 2:
      var value = new proto.resultstoresearch.v1.LineCoverage;
      reader.readMessage(value,proto.resultstoresearch.v1.LineCoverage.deserializeBinaryFromReader);
      msg.setLineCoverage(value);
      break;
    case 3:
      var value = new proto.resultstoresearch.v1.BranchCoverage;
      reader.readMessage(value,proto.resultstoresearch.v1.BranchCoverage.deserializeBinaryFromReader);
      msg.setBranchCoverage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resultstoresearch.v1.FileCoverage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.resultstoresearch.v1.FileCoverage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resultstoresearch.v1.FileCoverage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resultstoresearch.v1.FileCoverage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLineCoverage();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.resultstoresearch.v1.LineCoverage.serializeBinaryToWriter
    );
  }
  f = message.getBranchCoverage();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.resultstoresearch.v1.BranchCoverage.serializeBinaryToWriter
    );
  }
};


/**
 * optional string path = 1;
 * @return {string}
 */
proto.resultstoresearch.v1.FileCoverage.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.FileCoverage} returns this
 */
proto.resultstoresearch.v1.FileCoverage.prototype.setPath = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional LineCoverage line_coverage = 2;
 * @return {?proto.resultstoresearch.v1.LineCoverage}
 */
proto.resultstoresearch.v1.FileCoverage.prototype.getLineCoverage = function() {
  return /** @type{?proto.resultstoresearch.v1.LineCoverage} */ (
    jspb.Message.getWrapperField(this, proto.resultstoresearch.v1.LineCoverage, 2));
};


/**
 * @param {?proto.resultstoresearch.v1.LineCoverage|undefined} value
 * @return {!proto.resultstoresearch.v1.FileCoverage} returns this
*/
proto.resultstoresearch.v1.FileCoverage.prototype.setLineCoverage = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.resultstoresearch.v1.FileCoverage} returns this
 */
proto.resultstoresearch.v1.FileCoverage.prototype.clearLineCoverage = function() {
  return this.setLineCoverage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resultstoresearch.v1.FileCoverage.prototype.hasLineCoverage = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional BranchCoverage branch_coverage = 3;
 * @return {?proto.resultstoresearch.v1.BranchCoverage}
 */
proto.resultstoresearch.v1.FileCoverage.prototype.getBranchCoverage = function() {
  return /** @type{?proto.resultstoresearch.v1.BranchCoverage} */ (
    jspb.Message.getWrapperField(this, proto.resultstoresearch.v1.BranchCoverage, 3));
};


/**
 * @param {?proto.resultstoresearch.v1.BranchCoverage|undefined} value
 * @return {!proto.resultstoresearch.v1.FileCoverage} returns this
*/
proto.resultstoresearch.v1.FileCoverage.prototype.setBranchCoverage = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.resultstoresearch.v1.FileCoverage} returns this
 */
proto.resultstoresearch.v1.FileCoverage.prototype.clearBranchCoverage = function() {
  return this.setBranchCoverage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resultstoresearch.v1.FileCoverage.prototype.hasBranchCoverage = function() {
  return jspb.Message.getField(this, 3) != null;
};


