// source: file.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var wrappers_pb = require('./wrappers_pb.js');
goog.object.extend(proto, wrappers_pb);
goog.exportSymbol('proto.resultstoresearch.v1.ArchiveEntry', null, global);
goog.exportSymbol('proto.resultstoresearch.v1.File', null, global);
goog.exportSymbol('proto.resultstoresearch.v1.File.HashType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resultstoresearch.v1.File = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resultstoresearch.v1.File, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.resultstoresearch.v1.File.displayName =
        'proto.resultstoresearch.v1.File';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resultstoresearch.v1.ArchiveEntry = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resultstoresearch.v1.ArchiveEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.resultstoresearch.v1.ArchiveEntry.displayName =
        'proto.resultstoresearch.v1.ArchiveEntry';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.resultstoresearch.v1.File.prototype.toObject = function (
        opt_includeInstance
    ) {
        return proto.resultstoresearch.v1.File.toObject(
            opt_includeInstance,
            this
        );
    };

    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.resultstoresearch.v1.File} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.resultstoresearch.v1.File.toObject = function (includeInstance, msg) {
        var f,
            obj = {
                uid: jspb.Message.getFieldWithDefault(msg, 1, ''),
                uri: jspb.Message.getFieldWithDefault(msg, 2, ''),
                length:
                    (f = msg.getLength()) &&
                    wrappers_pb.Int64Value.toObject(includeInstance, f),
                contentType: jspb.Message.getFieldWithDefault(msg, 4, ''),
                archiveEntry:
                    (f = msg.getArchiveEntry()) &&
                    proto.resultstoresearch.v1.ArchiveEntry.toObject(
                        includeInstance,
                        f
                    ),
                contentViewer: jspb.Message.getFieldWithDefault(msg, 6, ''),
                hidden: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
                description: jspb.Message.getFieldWithDefault(msg, 8, ''),
                digest: jspb.Message.getFieldWithDefault(msg, 9, ''),
                hashType: jspb.Message.getFieldWithDefault(msg, 10, 0),
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resultstoresearch.v1.File}
 */
proto.resultstoresearch.v1.File.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.resultstoresearch.v1.File();
    return proto.resultstoresearch.v1.File.deserializeBinaryFromReader(
        msg,
        reader
    );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resultstoresearch.v1.File} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resultstoresearch.v1.File}
 */
proto.resultstoresearch.v1.File.deserializeBinaryFromReader = function (
    msg,
    reader
) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {string} */ (reader.readString());
                msg.setUid(value);
                break;
            case 2:
                var value = /** @type {string} */ (reader.readString());
                msg.setUri(value);
                break;
            case 3:
                var value = new wrappers_pb.Int64Value();
                reader.readMessage(
                    value,
                    wrappers_pb.Int64Value.deserializeBinaryFromReader
                );
                msg.setLength(value);
                break;
            case 4:
                var value = /** @type {string} */ (reader.readString());
                msg.setContentType(value);
                break;
            case 5:
                var value = new proto.resultstoresearch.v1.ArchiveEntry();
                reader.readMessage(
                    value,
                    proto.resultstoresearch.v1.ArchiveEntry
                        .deserializeBinaryFromReader
                );
                msg.setArchiveEntry(value);
                break;
            case 6:
                var value = /** @type {string} */ (reader.readString());
                msg.setContentViewer(value);
                break;
            case 7:
                var value = /** @type {boolean} */ (reader.readBool());
                msg.setHidden(value);
                break;
            case 8:
                var value = /** @type {string} */ (reader.readString());
                msg.setDescription(value);
                break;
            case 9:
                var value = /** @type {string} */ (reader.readString());
                msg.setDigest(value);
                break;
            case 10:
                var value = /** @type {!proto.resultstoresearch.v1.File.HashType} */ (reader.readEnum());
                msg.setHashType(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resultstoresearch.v1.File.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    proto.resultstoresearch.v1.File.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resultstoresearch.v1.File} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resultstoresearch.v1.File.serializeBinaryToWriter = function (
    message,
    writer
) {
    var f = undefined;
    f = message.getUid();
    if (f.length > 0) {
        writer.writeString(1, f);
    }
    f = message.getUri();
    if (f.length > 0) {
        writer.writeString(2, f);
    }
    f = message.getLength();
    if (f != null) {
        writer.writeMessage(
            3,
            f,
            wrappers_pb.Int64Value.serializeBinaryToWriter
        );
    }
    f = message.getContentType();
    if (f.length > 0) {
        writer.writeString(4, f);
    }
    f = message.getArchiveEntry();
    if (f != null) {
        writer.writeMessage(
            5,
            f,
            proto.resultstoresearch.v1.ArchiveEntry.serializeBinaryToWriter
        );
    }
    f = message.getContentViewer();
    if (f.length > 0) {
        writer.writeString(6, f);
    }
    f = message.getHidden();
    if (f) {
        writer.writeBool(7, f);
    }
    f = message.getDescription();
    if (f.length > 0) {
        writer.writeString(8, f);
    }
    f = message.getDigest();
    if (f.length > 0) {
        writer.writeString(9, f);
    }
    f = message.getHashType();
    if (f !== 0.0) {
        writer.writeEnum(10, f);
    }
};

/**
 * @enum {number}
 */
proto.resultstoresearch.v1.File.HashType = {
    HASH_TYPE_UNSPECIFIED: 0,
    MD5: 1,
    SHA1: 2,
    SHA256: 3,
};

/**
 * optional string uid = 1;
 * @return {string}
 */
proto.resultstoresearch.v1.File.prototype.getUid = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(
        this,
        1,
        ''
    ));
};

/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.File} returns this
 */
proto.resultstoresearch.v1.File.prototype.setUid = function (value) {
    return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string uri = 2;
 * @return {string}
 */
proto.resultstoresearch.v1.File.prototype.getUri = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(
        this,
        2,
        ''
    ));
};

/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.File} returns this
 */
proto.resultstoresearch.v1.File.prototype.setUri = function (value) {
    return jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * optional Int64Value length = 3;
 * @return {?proto.resultstoresearch.v1.Int64Value}
 */
proto.resultstoresearch.v1.File.prototype.getLength = function () {
    return /** @type{?proto.resultstoresearch.v1.Int64Value} */ (jspb.Message.getWrapperField(
        this,
        wrappers_pb.Int64Value,
        3
    ));
};

/**
 * @param {?proto.resultstoresearch.v1.Int64Value|undefined} value
 * @return {!proto.resultstoresearch.v1.File} returns this
 */
proto.resultstoresearch.v1.File.prototype.setLength = function (value) {
    return jspb.Message.setWrapperField(this, 3, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.resultstoresearch.v1.File} returns this
 */
proto.resultstoresearch.v1.File.prototype.clearLength = function () {
    return this.setLength(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resultstoresearch.v1.File.prototype.hasLength = function () {
    return jspb.Message.getField(this, 3) != null;
};

/**
 * optional string content_type = 4;
 * @return {string}
 */
proto.resultstoresearch.v1.File.prototype.getContentType = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(
        this,
        4,
        ''
    ));
};

/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.File} returns this
 */
proto.resultstoresearch.v1.File.prototype.setContentType = function (value) {
    return jspb.Message.setProto3StringField(this, 4, value);
};

/**
 * optional ArchiveEntry archive_entry = 5;
 * @return {?proto.resultstoresearch.v1.ArchiveEntry}
 */
proto.resultstoresearch.v1.File.prototype.getArchiveEntry = function () {
    return /** @type{?proto.resultstoresearch.v1.ArchiveEntry} */ (jspb.Message.getWrapperField(
        this,
        proto.resultstoresearch.v1.ArchiveEntry,
        5
    ));
};

/**
 * @param {?proto.resultstoresearch.v1.ArchiveEntry|undefined} value
 * @return {!proto.resultstoresearch.v1.File} returns this
 */
proto.resultstoresearch.v1.File.prototype.setArchiveEntry = function (value) {
    return jspb.Message.setWrapperField(this, 5, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.resultstoresearch.v1.File} returns this
 */
proto.resultstoresearch.v1.File.prototype.clearArchiveEntry = function () {
    return this.setArchiveEntry(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resultstoresearch.v1.File.prototype.hasArchiveEntry = function () {
    return jspb.Message.getField(this, 5) != null;
};

/**
 * optional string content_viewer = 6;
 * @return {string}
 */
proto.resultstoresearch.v1.File.prototype.getContentViewer = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(
        this,
        6,
        ''
    ));
};

/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.File} returns this
 */
proto.resultstoresearch.v1.File.prototype.setContentViewer = function (value) {
    return jspb.Message.setProto3StringField(this, 6, value);
};

/**
 * optional bool hidden = 7;
 * @return {boolean}
 */
proto.resultstoresearch.v1.File.prototype.getHidden = function () {
    return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(
        this,
        7,
        false
    ));
};

/**
 * @param {boolean} value
 * @return {!proto.resultstoresearch.v1.File} returns this
 */
proto.resultstoresearch.v1.File.prototype.setHidden = function (value) {
    return jspb.Message.setProto3BooleanField(this, 7, value);
};

/**
 * optional string description = 8;
 * @return {string}
 */
proto.resultstoresearch.v1.File.prototype.getDescription = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(
        this,
        8,
        ''
    ));
};

/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.File} returns this
 */
proto.resultstoresearch.v1.File.prototype.setDescription = function (value) {
    return jspb.Message.setProto3StringField(this, 8, value);
};

/**
 * optional string digest = 9;
 * @return {string}
 */
proto.resultstoresearch.v1.File.prototype.getDigest = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(
        this,
        9,
        ''
    ));
};

/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.File} returns this
 */
proto.resultstoresearch.v1.File.prototype.setDigest = function (value) {
    return jspb.Message.setProto3StringField(this, 9, value);
};

/**
 * optional HashType hash_type = 10;
 * @return {!proto.resultstoresearch.v1.File.HashType}
 */
proto.resultstoresearch.v1.File.prototype.getHashType = function () {
    return /** @type {!proto.resultstoresearch.v1.File.HashType} */ (jspb.Message.getFieldWithDefault(
        this,
        10,
        0
    ));
};

/**
 * @param {!proto.resultstoresearch.v1.File.HashType} value
 * @return {!proto.resultstoresearch.v1.File} returns this
 */
proto.resultstoresearch.v1.File.prototype.setHashType = function (value) {
    return jspb.Message.setProto3EnumField(this, 10, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.resultstoresearch.v1.ArchiveEntry.prototype.toObject = function (
        opt_includeInstance
    ) {
        return proto.resultstoresearch.v1.ArchiveEntry.toObject(
            opt_includeInstance,
            this
        );
    };

    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.resultstoresearch.v1.ArchiveEntry} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.resultstoresearch.v1.ArchiveEntry.toObject = function (
        includeInstance,
        msg
    ) {
        var f,
            obj = {
                path: jspb.Message.getFieldWithDefault(msg, 1, ''),
                length:
                    (f = msg.getLength()) &&
                    wrappers_pb.Int64Value.toObject(includeInstance, f),
                contentType: jspb.Message.getFieldWithDefault(msg, 3, ''),
            };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resultstoresearch.v1.ArchiveEntry}
 */
proto.resultstoresearch.v1.ArchiveEntry.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.resultstoresearch.v1.ArchiveEntry();
    return proto.resultstoresearch.v1.ArchiveEntry.deserializeBinaryFromReader(
        msg,
        reader
    );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resultstoresearch.v1.ArchiveEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resultstoresearch.v1.ArchiveEntry}
 */
proto.resultstoresearch.v1.ArchiveEntry.deserializeBinaryFromReader = function (
    msg,
    reader
) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {string} */ (reader.readString());
                msg.setPath(value);
                break;
            case 2:
                var value = new wrappers_pb.Int64Value();
                reader.readMessage(
                    value,
                    wrappers_pb.Int64Value.deserializeBinaryFromReader
                );
                msg.setLength(value);
                break;
            case 3:
                var value = /** @type {string} */ (reader.readString());
                msg.setContentType(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resultstoresearch.v1.ArchiveEntry.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    proto.resultstoresearch.v1.ArchiveEntry.serializeBinaryToWriter(
        this,
        writer
    );
    return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resultstoresearch.v1.ArchiveEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resultstoresearch.v1.ArchiveEntry.serializeBinaryToWriter = function (
    message,
    writer
) {
    var f = undefined;
    f = message.getPath();
    if (f.length > 0) {
        writer.writeString(1, f);
    }
    f = message.getLength();
    if (f != null) {
        writer.writeMessage(
            2,
            f,
            wrappers_pb.Int64Value.serializeBinaryToWriter
        );
    }
    f = message.getContentType();
    if (f.length > 0) {
        writer.writeString(3, f);
    }
};

/**
 * optional string path = 1;
 * @return {string}
 */
proto.resultstoresearch.v1.ArchiveEntry.prototype.getPath = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(
        this,
        1,
        ''
    ));
};

/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.ArchiveEntry} returns this
 */
proto.resultstoresearch.v1.ArchiveEntry.prototype.setPath = function (value) {
    return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional Int64Value length = 2;
 * @return {?proto.resultstoresearch.v1.Int64Value}
 */
proto.resultstoresearch.v1.ArchiveEntry.prototype.getLength = function () {
    return /** @type{?proto.resultstoresearch.v1.Int64Value} */ (jspb.Message.getWrapperField(
        this,
        wrappers_pb.Int64Value,
        2
    ));
};

/**
 * @param {?proto.resultstoresearch.v1.Int64Value|undefined} value
 * @return {!proto.resultstoresearch.v1.ArchiveEntry} returns this
 */
proto.resultstoresearch.v1.ArchiveEntry.prototype.setLength = function (value) {
    return jspb.Message.setWrapperField(this, 2, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.resultstoresearch.v1.ArchiveEntry} returns this
 */
proto.resultstoresearch.v1.ArchiveEntry.prototype.clearLength = function () {
    return this.setLength(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resultstoresearch.v1.ArchiveEntry.prototype.hasLength = function () {
    return jspb.Message.getField(this, 2) != null;
};

/**
 * optional string content_type = 3;
 * @return {string}
 */
proto.resultstoresearch.v1.ArchiveEntry.prototype.getContentType = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(
        this,
        3,
        ''
    ));
};

/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.ArchiveEntry} returns this
 */
proto.resultstoresearch.v1.ArchiveEntry.prototype.setContentType = function (
    value
) {
    return jspb.Message.setProto3StringField(this, 3, value);
};

goog.object.extend(exports, proto.resultstoresearch.v1);
