// source: invocation.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */

goog.provide('proto.resultstoresearch.v1.InvocationAttributes');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.resultstoresearch.v1.InvocationContext');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resultstoresearch.v1.InvocationAttributes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.resultstoresearch.v1.InvocationAttributes.repeatedFields_, null);
};
goog.inherits(proto.resultstoresearch.v1.InvocationAttributes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.resultstoresearch.v1.InvocationAttributes.displayName = 'proto.resultstoresearch.v1.InvocationAttributes';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.resultstoresearch.v1.InvocationAttributes.repeatedFields_ = [2,3,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resultstoresearch.v1.InvocationAttributes.prototype.toObject = function(opt_includeInstance) {
  return proto.resultstoresearch.v1.InvocationAttributes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resultstoresearch.v1.InvocationAttributes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resultstoresearch.v1.InvocationAttributes.toObject = function(includeInstance, msg) {
  var f, obj = {
    projectId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    usersList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    labelsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    description: jspb.Message.getFieldWithDefault(msg, 4, ""),
    invocationContextsList: jspb.Message.toObjectList(msg.getInvocationContextsList(),
    proto.resultstoresearch.v1.InvocationContext.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resultstoresearch.v1.InvocationAttributes}
 */
proto.resultstoresearch.v1.InvocationAttributes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resultstoresearch.v1.InvocationAttributes;
  return proto.resultstoresearch.v1.InvocationAttributes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resultstoresearch.v1.InvocationAttributes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resultstoresearch.v1.InvocationAttributes}
 */
proto.resultstoresearch.v1.InvocationAttributes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProjectId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addUsers(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addLabels(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 6:
      var value = new proto.resultstoresearch.v1.InvocationContext;
      reader.readMessage(value,proto.resultstoresearch.v1.InvocationContext.deserializeBinaryFromReader);
      msg.addInvocationContexts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resultstoresearch.v1.InvocationAttributes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.resultstoresearch.v1.InvocationAttributes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resultstoresearch.v1.InvocationAttributes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resultstoresearch.v1.InvocationAttributes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProjectId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUsersList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getLabelsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getInvocationContextsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.resultstoresearch.v1.InvocationContext.serializeBinaryToWriter
    );
  }
};


/**
 * optional string project_id = 1;
 * @return {string}
 */
proto.resultstoresearch.v1.InvocationAttributes.prototype.getProjectId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.InvocationAttributes} returns this
 */
proto.resultstoresearch.v1.InvocationAttributes.prototype.setProjectId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string users = 2;
 * @return {!Array<string>}
 */
proto.resultstoresearch.v1.InvocationAttributes.prototype.getUsersList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.resultstoresearch.v1.InvocationAttributes} returns this
 */
proto.resultstoresearch.v1.InvocationAttributes.prototype.setUsersList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.resultstoresearch.v1.InvocationAttributes} returns this
 */
proto.resultstoresearch.v1.InvocationAttributes.prototype.addUsers = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.resultstoresearch.v1.InvocationAttributes} returns this
 */
proto.resultstoresearch.v1.InvocationAttributes.prototype.clearUsersList = function() {
  return this.setUsersList([]);
};


/**
 * repeated string labels = 3;
 * @return {!Array<string>}
 */
proto.resultstoresearch.v1.InvocationAttributes.prototype.getLabelsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.resultstoresearch.v1.InvocationAttributes} returns this
 */
proto.resultstoresearch.v1.InvocationAttributes.prototype.setLabelsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.resultstoresearch.v1.InvocationAttributes} returns this
 */
proto.resultstoresearch.v1.InvocationAttributes.prototype.addLabels = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.resultstoresearch.v1.InvocationAttributes} returns this
 */
proto.resultstoresearch.v1.InvocationAttributes.prototype.clearLabelsList = function() {
  return this.setLabelsList([]);
};


/**
 * optional string description = 4;
 * @return {string}
 */
proto.resultstoresearch.v1.InvocationAttributes.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.InvocationAttributes} returns this
 */
proto.resultstoresearch.v1.InvocationAttributes.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated InvocationContext invocation_contexts = 6;
 * @return {!Array<!proto.resultstoresearch.v1.InvocationContext>}
 */
proto.resultstoresearch.v1.InvocationAttributes.prototype.getInvocationContextsList = function() {
  return /** @type{!Array<!proto.resultstoresearch.v1.InvocationContext>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.resultstoresearch.v1.InvocationContext, 6));
};


/**
 * @param {!Array<!proto.resultstoresearch.v1.InvocationContext>} value
 * @return {!proto.resultstoresearch.v1.InvocationAttributes} returns this
*/
proto.resultstoresearch.v1.InvocationAttributes.prototype.setInvocationContextsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.resultstoresearch.v1.InvocationContext=} opt_value
 * @param {number=} opt_index
 * @return {!proto.resultstoresearch.v1.InvocationContext}
 */
proto.resultstoresearch.v1.InvocationAttributes.prototype.addInvocationContexts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.resultstoresearch.v1.InvocationContext, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.resultstoresearch.v1.InvocationAttributes} returns this
 */
proto.resultstoresearch.v1.InvocationAttributes.prototype.clearInvocationContextsList = function() {
  return this.setInvocationContextsList([]);
};


