// source: coverage.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */

goog.provide('proto.resultstoresearch.v1.LineCoverage');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resultstoresearch.v1.LineCoverage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.resultstoresearch.v1.LineCoverage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.resultstoresearch.v1.LineCoverage.displayName = 'proto.resultstoresearch.v1.LineCoverage';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resultstoresearch.v1.LineCoverage.prototype.toObject = function(opt_includeInstance) {
  return proto.resultstoresearch.v1.LineCoverage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resultstoresearch.v1.LineCoverage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resultstoresearch.v1.LineCoverage.toObject = function(includeInstance, msg) {
  var f, obj = {
    instrumentedLines: msg.getInstrumentedLines_asB64(),
    executedLines: msg.getExecutedLines_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resultstoresearch.v1.LineCoverage}
 */
proto.resultstoresearch.v1.LineCoverage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resultstoresearch.v1.LineCoverage;
  return proto.resultstoresearch.v1.LineCoverage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resultstoresearch.v1.LineCoverage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resultstoresearch.v1.LineCoverage}
 */
proto.resultstoresearch.v1.LineCoverage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setInstrumentedLines(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setExecutedLines(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resultstoresearch.v1.LineCoverage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.resultstoresearch.v1.LineCoverage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resultstoresearch.v1.LineCoverage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resultstoresearch.v1.LineCoverage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInstrumentedLines_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getExecutedLines_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
};


/**
 * optional bytes instrumented_lines = 1;
 * @return {string}
 */
proto.resultstoresearch.v1.LineCoverage.prototype.getInstrumentedLines = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes instrumented_lines = 1;
 * This is a type-conversion wrapper around `getInstrumentedLines()`
 * @return {string}
 */
proto.resultstoresearch.v1.LineCoverage.prototype.getInstrumentedLines_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getInstrumentedLines()));
};


/**
 * optional bytes instrumented_lines = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getInstrumentedLines()`
 * @return {!Uint8Array}
 */
proto.resultstoresearch.v1.LineCoverage.prototype.getInstrumentedLines_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getInstrumentedLines()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.resultstoresearch.v1.LineCoverage} returns this
 */
proto.resultstoresearch.v1.LineCoverage.prototype.setInstrumentedLines = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bytes executed_lines = 2;
 * @return {string}
 */
proto.resultstoresearch.v1.LineCoverage.prototype.getExecutedLines = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes executed_lines = 2;
 * This is a type-conversion wrapper around `getExecutedLines()`
 * @return {string}
 */
proto.resultstoresearch.v1.LineCoverage.prototype.getExecutedLines_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getExecutedLines()));
};


/**
 * optional bytes executed_lines = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getExecutedLines()`
 * @return {!Uint8Array}
 */
proto.resultstoresearch.v1.LineCoverage.prototype.getExecutedLines_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getExecutedLines()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.resultstoresearch.v1.LineCoverage} returns this
 */
proto.resultstoresearch.v1.LineCoverage.prototype.setExecutedLines = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


