// source: invocation.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* tslint:disable */
/* eslint-disable */

goog.provide('proto.resultstoresearch.v1.WorkspaceInfo');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.resultstoresearch.v1.CommandLine');
goog.require('proto.resultstoresearch.v1.WorkspaceContext');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.resultstoresearch.v1.WorkspaceInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.resultstoresearch.v1.WorkspaceInfo.repeatedFields_, null);
};
goog.inherits(proto.resultstoresearch.v1.WorkspaceInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.resultstoresearch.v1.WorkspaceInfo.displayName = 'proto.resultstoresearch.v1.WorkspaceInfo';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.resultstoresearch.v1.WorkspaceInfo.repeatedFields_ = [7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.resultstoresearch.v1.WorkspaceInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.resultstoresearch.v1.WorkspaceInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.resultstoresearch.v1.WorkspaceInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resultstoresearch.v1.WorkspaceInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    workspaceContext: (f = msg.getWorkspaceContext()) && proto.resultstoresearch.v1.WorkspaceContext.toObject(includeInstance, f),
    hostname: jspb.Message.getFieldWithDefault(msg, 3, ""),
    workingDirectory: jspb.Message.getFieldWithDefault(msg, 4, ""),
    toolTag: jspb.Message.getFieldWithDefault(msg, 5, ""),
    commandLinesList: jspb.Message.toObjectList(msg.getCommandLinesList(),
    proto.resultstoresearch.v1.CommandLine.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.resultstoresearch.v1.WorkspaceInfo}
 */
proto.resultstoresearch.v1.WorkspaceInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.resultstoresearch.v1.WorkspaceInfo;
  return proto.resultstoresearch.v1.WorkspaceInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.resultstoresearch.v1.WorkspaceInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.resultstoresearch.v1.WorkspaceInfo}
 */
proto.resultstoresearch.v1.WorkspaceInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.resultstoresearch.v1.WorkspaceContext;
      reader.readMessage(value,proto.resultstoresearch.v1.WorkspaceContext.deserializeBinaryFromReader);
      msg.setWorkspaceContext(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setHostname(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkingDirectory(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setToolTag(value);
      break;
    case 7:
      var value = new proto.resultstoresearch.v1.CommandLine;
      reader.readMessage(value,proto.resultstoresearch.v1.CommandLine.deserializeBinaryFromReader);
      msg.addCommandLines(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.resultstoresearch.v1.WorkspaceInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.resultstoresearch.v1.WorkspaceInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.resultstoresearch.v1.WorkspaceInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.resultstoresearch.v1.WorkspaceInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWorkspaceContext();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.resultstoresearch.v1.WorkspaceContext.serializeBinaryToWriter
    );
  }
  f = message.getHostname();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getWorkingDirectory();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getToolTag();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCommandLinesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.resultstoresearch.v1.CommandLine.serializeBinaryToWriter
    );
  }
};


/**
 * optional WorkspaceContext workspace_context = 1;
 * @return {?proto.resultstoresearch.v1.WorkspaceContext}
 */
proto.resultstoresearch.v1.WorkspaceInfo.prototype.getWorkspaceContext = function() {
  return /** @type{?proto.resultstoresearch.v1.WorkspaceContext} */ (
    jspb.Message.getWrapperField(this, proto.resultstoresearch.v1.WorkspaceContext, 1));
};


/**
 * @param {?proto.resultstoresearch.v1.WorkspaceContext|undefined} value
 * @return {!proto.resultstoresearch.v1.WorkspaceInfo} returns this
*/
proto.resultstoresearch.v1.WorkspaceInfo.prototype.setWorkspaceContext = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.resultstoresearch.v1.WorkspaceInfo} returns this
 */
proto.resultstoresearch.v1.WorkspaceInfo.prototype.clearWorkspaceContext = function() {
  return this.setWorkspaceContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.resultstoresearch.v1.WorkspaceInfo.prototype.hasWorkspaceContext = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string hostname = 3;
 * @return {string}
 */
proto.resultstoresearch.v1.WorkspaceInfo.prototype.getHostname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.WorkspaceInfo} returns this
 */
proto.resultstoresearch.v1.WorkspaceInfo.prototype.setHostname = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string working_directory = 4;
 * @return {string}
 */
proto.resultstoresearch.v1.WorkspaceInfo.prototype.getWorkingDirectory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.WorkspaceInfo} returns this
 */
proto.resultstoresearch.v1.WorkspaceInfo.prototype.setWorkingDirectory = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string tool_tag = 5;
 * @return {string}
 */
proto.resultstoresearch.v1.WorkspaceInfo.prototype.getToolTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.resultstoresearch.v1.WorkspaceInfo} returns this
 */
proto.resultstoresearch.v1.WorkspaceInfo.prototype.setToolTag = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * repeated CommandLine command_lines = 7;
 * @return {!Array<!proto.resultstoresearch.v1.CommandLine>}
 */
proto.resultstoresearch.v1.WorkspaceInfo.prototype.getCommandLinesList = function() {
  return /** @type{!Array<!proto.resultstoresearch.v1.CommandLine>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.resultstoresearch.v1.CommandLine, 7));
};


/**
 * @param {!Array<!proto.resultstoresearch.v1.CommandLine>} value
 * @return {!proto.resultstoresearch.v1.WorkspaceInfo} returns this
*/
proto.resultstoresearch.v1.WorkspaceInfo.prototype.setCommandLinesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.resultstoresearch.v1.CommandLine=} opt_value
 * @param {number=} opt_index
 * @return {!proto.resultstoresearch.v1.CommandLine}
 */
proto.resultstoresearch.v1.WorkspaceInfo.prototype.addCommandLines = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.resultstoresearch.v1.CommandLine, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.resultstoresearch.v1.WorkspaceInfo} returns this
 */
proto.resultstoresearch.v1.WorkspaceInfo.prototype.clearCommandLinesList = function() {
  return this.setCommandLinesList([]);
};


