version: "3.8"
services:
  envoy:
    build:
      context: ./resultstore-search-client/envoy/
      network: host
    ports:
      - "8080:8080"
      - "9901:9901" 

  server:
    build:
      context: ./resultstore-search-api/
    volumes:
      - ./resultstore-search-api/:/usr/src/app
    ports:
      - "9090:9090"
  
  client:
    build:
      context: ./resultstore-search-client/
    volumes:
      - ./resultstore-search-client/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    depends_on:
      - server
      - envoy
