# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coverage_summary.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import resultstoresearchapi.common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='coverage_summary.proto',
  package='resultstoresearch.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x16\x63overage_summary.proto\x12\x14resultstoresearch.v1\x1a\x0c\x63ommon.proto\"S\n\x13LineCoverageSummary\x12\x1f\n\x17instrumented_line_count\x18\x01 \x01(\x05\x12\x1b\n\x13\x65xecuted_line_count\x18\x02 \x01(\x05\"n\n\x15\x42ranchCoverageSummary\x12\x1a\n\x12total_branch_count\x18\x01 \x01(\x05\x12\x1d\n\x15\x65xecuted_branch_count\x18\x02 \x01(\x05\x12\x1a\n\x12taken_branch_count\x18\x03 \x01(\x05\"\xd1\x01\n\x17LanguageCoverageSummary\x12\x30\n\x08language\x18\x01 \x01(\x0e\x32\x1e.resultstoresearch.v1.Language\x12?\n\x0cline_summary\x18\x02 \x01(\x0b\x32).resultstoresearch.v1.LineCoverageSummary\x12\x43\n\x0e\x62ranch_summary\x18\x03 \x01(\x0b\x32+.resultstoresearch.v1.BranchCoverageSummaryb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_LINECOVERAGESUMMARY = _descriptor.Descriptor(
  name='LineCoverageSummary',
  full_name='resultstoresearch.v1.LineCoverageSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instrumented_line_count', full_name='resultstoresearch.v1.LineCoverageSummary.instrumented_line_count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='executed_line_count', full_name='resultstoresearch.v1.LineCoverageSummary.executed_line_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=145,
)


_BRANCHCOVERAGESUMMARY = _descriptor.Descriptor(
  name='BranchCoverageSummary',
  full_name='resultstoresearch.v1.BranchCoverageSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_branch_count', full_name='resultstoresearch.v1.BranchCoverageSummary.total_branch_count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='executed_branch_count', full_name='resultstoresearch.v1.BranchCoverageSummary.executed_branch_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='taken_branch_count', full_name='resultstoresearch.v1.BranchCoverageSummary.taken_branch_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=257,
)


_LANGUAGECOVERAGESUMMARY = _descriptor.Descriptor(
  name='LanguageCoverageSummary',
  full_name='resultstoresearch.v1.LanguageCoverageSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='language', full_name='resultstoresearch.v1.LanguageCoverageSummary.language', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='line_summary', full_name='resultstoresearch.v1.LanguageCoverageSummary.line_summary', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='branch_summary', full_name='resultstoresearch.v1.LanguageCoverageSummary.branch_summary', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=469,
)

_LANGUAGECOVERAGESUMMARY.fields_by_name['language'].enum_type = common__pb2._LANGUAGE
_LANGUAGECOVERAGESUMMARY.fields_by_name['line_summary'].message_type = _LINECOVERAGESUMMARY
_LANGUAGECOVERAGESUMMARY.fields_by_name['branch_summary'].message_type = _BRANCHCOVERAGESUMMARY
DESCRIPTOR.message_types_by_name['LineCoverageSummary'] = _LINECOVERAGESUMMARY
DESCRIPTOR.message_types_by_name['BranchCoverageSummary'] = _BRANCHCOVERAGESUMMARY
DESCRIPTOR.message_types_by_name['LanguageCoverageSummary'] = _LANGUAGECOVERAGESUMMARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LineCoverageSummary = _reflection.GeneratedProtocolMessageType('LineCoverageSummary', (_message.Message,), {
  'DESCRIPTOR' : _LINECOVERAGESUMMARY,
  '__module__' : 'coverage_summary_pb2'
  # @@protoc_insertion_point(class_scope:resultstoresearch.v1.LineCoverageSummary)
  })
_sym_db.RegisterMessage(LineCoverageSummary)

BranchCoverageSummary = _reflection.GeneratedProtocolMessageType('BranchCoverageSummary', (_message.Message,), {
  'DESCRIPTOR' : _BRANCHCOVERAGESUMMARY,
  '__module__' : 'coverage_summary_pb2'
  # @@protoc_insertion_point(class_scope:resultstoresearch.v1.BranchCoverageSummary)
  })
_sym_db.RegisterMessage(BranchCoverageSummary)

LanguageCoverageSummary = _reflection.GeneratedProtocolMessageType('LanguageCoverageSummary', (_message.Message,), {
  'DESCRIPTOR' : _LANGUAGECOVERAGESUMMARY,
  '__module__' : 'coverage_summary_pb2'
  # @@protoc_insertion_point(class_scope:resultstoresearch.v1.LanguageCoverageSummary)
  })
_sym_db.RegisterMessage(LanguageCoverageSummary)


# @@protoc_insertion_point(module_scope)
