# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resultstore_download.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import resultstoresearchapi.invocation_pb2 as invocation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='resultstore_download.proto',
  package='resultstoresearch.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1aresultstore_download.proto\x12\x14resultstoresearch.v1\x1a\x10invocation.proto\"\x9b\x01\n\x18SearchInvocationsRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x14\n\npage_token\x18\x02 \x01(\tH\x00\x12\x10\n\x06offset\x18\x03 \x01(\x03H\x00\x12\r\n\x05query\x18\x04 \x01(\t\x12\x12\n\nproject_id\x18\x05 \x01(\t\x12\x13\n\x0b\x65xact_match\x18\x07 \x01(\x08\x42\x0c\n\npage_start\"$\n\x14GetInvocationRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"k\n\x19SearchInvocationsResponse\x12\x35\n\x0binvocations\x18\x01 \x03(\x0b\x32 .resultstoresearch.v1.Invocation\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t2\xea\x01\n\x13ResultStoreDownload\x12t\n\x11SearchInvocations\x12..resultstoresearch.v1.SearchInvocationsRequest\x1a/.resultstoresearch.v1.SearchInvocationsResponse\x12]\n\rGetInvocation\x12*.resultstoresearch.v1.GetInvocationRequest\x1a .resultstoresearch.v1.Invocationb\x06proto3'
  ,
  dependencies=[invocation__pb2.DESCRIPTOR,])




_SEARCHINVOCATIONSREQUEST = _descriptor.Descriptor(
  name='SearchInvocationsRequest',
  full_name='resultstoresearch.v1.SearchInvocationsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='page_size', full_name='resultstoresearch.v1.SearchInvocationsRequest.page_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_token', full_name='resultstoresearch.v1.SearchInvocationsRequest.page_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='resultstoresearch.v1.SearchInvocationsRequest.offset', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='query', full_name='resultstoresearch.v1.SearchInvocationsRequest.query', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='project_id', full_name='resultstoresearch.v1.SearchInvocationsRequest.project_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exact_match', full_name='resultstoresearch.v1.SearchInvocationsRequest.exact_match', index=5,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='page_start', full_name='resultstoresearch.v1.SearchInvocationsRequest.page_start',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=71,
  serialized_end=226,
)


_GETINVOCATIONREQUEST = _descriptor.Descriptor(
  name='GetInvocationRequest',
  full_name='resultstoresearch.v1.GetInvocationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='resultstoresearch.v1.GetInvocationRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=264,
)


_SEARCHINVOCATIONSRESPONSE = _descriptor.Descriptor(
  name='SearchInvocationsResponse',
  full_name='resultstoresearch.v1.SearchInvocationsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='invocations', full_name='resultstoresearch.v1.SearchInvocationsResponse.invocations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_page_token', full_name='resultstoresearch.v1.SearchInvocationsResponse.next_page_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=373,
)

_SEARCHINVOCATIONSREQUEST.oneofs_by_name['page_start'].fields.append(
  _SEARCHINVOCATIONSREQUEST.fields_by_name['page_token'])
_SEARCHINVOCATIONSREQUEST.fields_by_name['page_token'].containing_oneof = _SEARCHINVOCATIONSREQUEST.oneofs_by_name['page_start']
_SEARCHINVOCATIONSREQUEST.oneofs_by_name['page_start'].fields.append(
  _SEARCHINVOCATIONSREQUEST.fields_by_name['offset'])
_SEARCHINVOCATIONSREQUEST.fields_by_name['offset'].containing_oneof = _SEARCHINVOCATIONSREQUEST.oneofs_by_name['page_start']
_SEARCHINVOCATIONSRESPONSE.fields_by_name['invocations'].message_type = invocation__pb2._INVOCATION
DESCRIPTOR.message_types_by_name['SearchInvocationsRequest'] = _SEARCHINVOCATIONSREQUEST
DESCRIPTOR.message_types_by_name['GetInvocationRequest'] = _GETINVOCATIONREQUEST
DESCRIPTOR.message_types_by_name['SearchInvocationsResponse'] = _SEARCHINVOCATIONSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchInvocationsRequest = _reflection.GeneratedProtocolMessageType('SearchInvocationsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHINVOCATIONSREQUEST,
  '__module__' : 'resultstore_download_pb2'
  # @@protoc_insertion_point(class_scope:resultstoresearch.v1.SearchInvocationsRequest)
  })
_sym_db.RegisterMessage(SearchInvocationsRequest)

GetInvocationRequest = _reflection.GeneratedProtocolMessageType('GetInvocationRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETINVOCATIONREQUEST,
  '__module__' : 'resultstore_download_pb2'
  # @@protoc_insertion_point(class_scope:resultstoresearch.v1.GetInvocationRequest)
  })
_sym_db.RegisterMessage(GetInvocationRequest)

SearchInvocationsResponse = _reflection.GeneratedProtocolMessageType('SearchInvocationsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHINVOCATIONSRESPONSE,
  '__module__' : 'resultstore_download_pb2'
  # @@protoc_insertion_point(class_scope:resultstoresearch.v1.SearchInvocationsResponse)
  })
_sym_db.RegisterMessage(SearchInvocationsResponse)



_RESULTSTOREDOWNLOAD = _descriptor.ServiceDescriptor(
  name='ResultStoreDownload',
  full_name='resultstoresearch.v1.ResultStoreDownload',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=376,
  serialized_end=610,
  methods=[
  _descriptor.MethodDescriptor(
    name='SearchInvocations',
    full_name='resultstoresearch.v1.ResultStoreDownload.SearchInvocations',
    index=0,
    containing_service=None,
    input_type=_SEARCHINVOCATIONSREQUEST,
    output_type=_SEARCHINVOCATIONSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetInvocation',
    full_name='resultstoresearch.v1.ResultStoreDownload.GetInvocation',
    index=1,
    containing_service=None,
    input_type=_GETINVOCATIONREQUEST,
    output_type=invocation__pb2._INVOCATION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RESULTSTOREDOWNLOAD)

DESCRIPTOR.services_by_name['ResultStoreDownload'] = _RESULTSTOREDOWNLOAD

# @@protoc_insertion_point(module_scope)
