CREATE USER docker;

CREATE DATABASE resultstore_search;

GRANT ALL PRIVILEGES ON DATABASE resultstore_search TO docker;

CREATE TABLE IF NOT EXISTS TOOL_TAGS (
    ID INT PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL)