FROM python:3

RUN pip install absl-py grpcio protobuf gcloud google-api-python-client google-api-python-client

ENV APP_HOME /usr/src/app
WORKDIR $APP_HOME
COPY . ./

CMD ["python3", "-u", "server.py"]
