# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/devtools/resultstore_v2/proto/configuration.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.cloud.devtools.resultstore_v2.proto import common_pb2 as google_dot_cloud_dot_devtools_dot_resultstore__v2_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/cloud/devtools/resultstore_v2/proto/configuration.proto',
  package='google.devtools.resultstore.v2',
  syntax='proto3',
  serialized_options=b'\n\"com.google.devtools.resultstore.v2P\001ZIgoogle.golang.org/genproto/googleapis/devtools/resultstore/v2;resultstore',
  serialized_pb=b'\n>google/cloud/devtools/resultstore_v2/proto/configuration.proto\x12\x1egoogle.devtools.resultstore.v2\x1a\x37google/cloud/devtools/resultstore_v2/proto/common.proto\"\x8e\x03\n\rConfiguration\x12\x0c\n\x04name\x18\x01 \x01(\t\x12<\n\x02id\x18\x02 \x01(\x0b\x32\x30.google.devtools.resultstore.v2.Configuration.Id\x12K\n\x11status_attributes\x18\x03 \x01(\x0b\x32\x30.google.devtools.resultstore.v2.StatusAttributes\x12Y\n\x18\x63onfiguration_attributes\x18\x05 \x01(\x0b\x32\x37.google.devtools.resultstore.v2.ConfigurationAttributes\x12<\n\nproperties\x18\x06 \x03(\x0b\x32(.google.devtools.resultstore.v2.Property\x12\x14\n\x0c\x64isplay_name\x18\x08 \x01(\t\x1a\x35\n\x02Id\x12\x15\n\rinvocation_id\x18\x01 \x01(\t\x12\x18\n\x10\x63onfiguration_id\x18\x02 \x01(\t\"&\n\x17\x43onfigurationAttributes\x12\x0b\n\x03\x63pu\x18\x01 \x01(\tBq\n\"com.google.devtools.resultstore.v2P\x01ZIgoogle.golang.org/genproto/googleapis/devtools/resultstore/v2;resultstoreb\x06proto3'
  ,
  dependencies=[google_dot_cloud_dot_devtools_dot_resultstore__v2_dot_proto_dot_common__pb2.DESCRIPTOR,])




_CONFIGURATION_ID = _descriptor.Descriptor(
  name='Id',
  full_name='google.devtools.resultstore.v2.Configuration.Id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='invocation_id', full_name='google.devtools.resultstore.v2.Configuration.Id.invocation_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='configuration_id', full_name='google.devtools.resultstore.v2.Configuration.Id.configuration_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=501,
  serialized_end=554,
)

_CONFIGURATION = _descriptor.Descriptor(
  name='Configuration',
  full_name='google.devtools.resultstore.v2.Configuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google.devtools.resultstore.v2.Configuration.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='google.devtools.resultstore.v2.Configuration.id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_attributes', full_name='google.devtools.resultstore.v2.Configuration.status_attributes', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='configuration_attributes', full_name='google.devtools.resultstore.v2.Configuration.configuration_attributes', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties', full_name='google.devtools.resultstore.v2.Configuration.properties', index=4,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='display_name', full_name='google.devtools.resultstore.v2.Configuration.display_name', index=5,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CONFIGURATION_ID, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=554,
)


_CONFIGURATIONATTRIBUTES = _descriptor.Descriptor(
  name='ConfigurationAttributes',
  full_name='google.devtools.resultstore.v2.ConfigurationAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpu', full_name='google.devtools.resultstore.v2.ConfigurationAttributes.cpu', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=556,
  serialized_end=594,
)

_CONFIGURATION_ID.containing_type = _CONFIGURATION
_CONFIGURATION.fields_by_name['id'].message_type = _CONFIGURATION_ID
_CONFIGURATION.fields_by_name['status_attributes'].message_type = google_dot_cloud_dot_devtools_dot_resultstore__v2_dot_proto_dot_common__pb2._STATUSATTRIBUTES
_CONFIGURATION.fields_by_name['configuration_attributes'].message_type = _CONFIGURATIONATTRIBUTES
_CONFIGURATION.fields_by_name['properties'].message_type = google_dot_cloud_dot_devtools_dot_resultstore__v2_dot_proto_dot_common__pb2._PROPERTY
DESCRIPTOR.message_types_by_name['Configuration'] = _CONFIGURATION
DESCRIPTOR.message_types_by_name['ConfigurationAttributes'] = _CONFIGURATIONATTRIBUTES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Configuration = _reflection.GeneratedProtocolMessageType('Configuration', (_message.Message,), {

  'Id' : _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), {
    'DESCRIPTOR' : _CONFIGURATION_ID,
    '__module__' : 'google.cloud.devtools.resultstore_v2.proto.configuration_pb2'
    ,
    '__doc__': """The resource ID components that identify the
    Configuration.
    
    
    Attributes:
        invocation_id:
            The Invocation ID.
        configuration_id:
            The Configuration ID.
    """,
    # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.Configuration.Id)
    })
  ,
  'DESCRIPTOR' : _CONFIGURATION,
  '__module__' : 'google.cloud.devtools.resultstore_v2.proto.configuration_pb2'
  ,
  '__doc__': """Represents a configuration within an Invocation associated
  with one or more ConfiguredTargets. It captures the environment and
  other settings that were used.
  
  
  Attributes:
      name:
          The format of this Configuration resource name must be:
          invocations/\ :math:`{INVOCATION_ID}/configs/`\
          {url_encode(CONFIG_ID)} The configuration ID of “default”
          should be preferred for the default configuration in a single-
          config invocation.
      id:
          The resource ID components that identify the Configuration.
          They must match the resource name after proper encoding.
      status_attributes:
          The aggregate status for this configuration.
      configuration_attributes:
          Attributes that apply only to this configuration.
      properties:
          Arbitrary name-value pairs. This is implemented as a multi-
          map. Multiple properties are allowed with the same key.
          Properties will be returned in lexicographical order by key.
      display_name:
          A human-readable name for Configuration. It is recommended
          that this name be unique. If omitted, the configuration_id
          should be used as display_name instead.
  """,
  # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.Configuration)
  })
_sym_db.RegisterMessage(Configuration)
_sym_db.RegisterMessage(Configuration.Id)

ConfigurationAttributes = _reflection.GeneratedProtocolMessageType('ConfigurationAttributes', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGURATIONATTRIBUTES,
  '__module__' : 'google.cloud.devtools.resultstore_v2.proto.configuration_pb2'
  ,
  '__doc__': """Attributes that apply only to the configuration.
  
  
  Attributes:
      cpu:
          The type of cpu. (e.g. “x86”, “powerpc”)
  """,
  # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.ConfigurationAttributes)
  })
_sym_db.RegisterMessage(ConfigurationAttributes)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
