# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/devtools/resultstore_v2/proto/file_set.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.cloud.devtools.resultstore_v2.proto import file_pb2 as google_dot_cloud_dot_devtools_dot_resultstore__v2_dot_proto_dot_file__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/cloud/devtools/resultstore_v2/proto/file_set.proto',
  package='google.devtools.resultstore.v2',
  syntax='proto3',
  serialized_options=b'\n\"com.google.devtools.resultstore.v2P\001ZIgoogle.golang.org/genproto/googleapis/devtools/resultstore/v2;resultstore',
  serialized_pb=b'\n9google/cloud/devtools/resultstore_v2/proto/file_set.proto\x12\x1egoogle.devtools.resultstore.v2\x1a\x35google/cloud/devtools/resultstore_v2/proto/file.proto\"\xc9\x01\n\x07\x46ileSet\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x36\n\x02id\x18\x02 \x01(\x0b\x32*.google.devtools.resultstore.v2.FileSet.Id\x12\x11\n\tfile_sets\x18\x03 \x03(\t\x12\x33\n\x05\x66iles\x18\x04 \x03(\x0b\x32$.google.devtools.resultstore.v2.File\x1a\x30\n\x02Id\x12\x15\n\rinvocation_id\x18\x01 \x01(\t\x12\x13\n\x0b\x66ile_set_id\x18\x02 \x01(\tBq\n\"com.google.devtools.resultstore.v2P\x01ZIgoogle.golang.org/genproto/googleapis/devtools/resultstore/v2;resultstoreb\x06proto3'
  ,
  dependencies=[google_dot_cloud_dot_devtools_dot_resultstore__v2_dot_proto_dot_file__pb2.DESCRIPTOR,])




_FILESET_ID = _descriptor.Descriptor(
  name='Id',
  full_name='google.devtools.resultstore.v2.FileSet.Id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='invocation_id', full_name='google.devtools.resultstore.v2.FileSet.Id.invocation_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_set_id', full_name='google.devtools.resultstore.v2.FileSet.Id.file_set_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=350,
)

_FILESET = _descriptor.Descriptor(
  name='FileSet',
  full_name='google.devtools.resultstore.v2.FileSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google.devtools.resultstore.v2.FileSet.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='google.devtools.resultstore.v2.FileSet.id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_sets', full_name='google.devtools.resultstore.v2.FileSet.file_sets', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='files', full_name='google.devtools.resultstore.v2.FileSet.files', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FILESET_ID, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=350,
)

_FILESET_ID.containing_type = _FILESET
_FILESET.fields_by_name['id'].message_type = _FILESET_ID
_FILESET.fields_by_name['files'].message_type = google_dot_cloud_dot_devtools_dot_resultstore__v2_dot_proto_dot_file__pb2._FILE
DESCRIPTOR.message_types_by_name['FileSet'] = _FILESET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileSet = _reflection.GeneratedProtocolMessageType('FileSet', (_message.Message,), {

  'Id' : _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), {
    'DESCRIPTOR' : _FILESET_ID,
    '__module__' : 'google.cloud.devtools.resultstore_v2.proto.file_set_pb2'
    ,
    '__doc__': """The resource ID components that identify the FileSet.
    
    
    Attributes:
        invocation_id:
            The Invocation ID.
        file_set_id:
            The FileSet ID.
    """,
    # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.FileSet.Id)
    })
  ,
  'DESCRIPTOR' : _FILESET,
  '__module__' : 'google.cloud.devtools.resultstore_v2.proto.file_set_pb2'
  ,
  '__doc__': """This resource represents a set of Files and other (nested)
  FileSets. A FileSet is a node in the graph, and the file_sets field
  represents the outgoing edges. A resource may reference various nodes in
  the graph to represent the transitive closure of all files from those
  nodes. The FileSets must form a directed acyclic graph. The Upload API
  is unable to enforce that the graph is acyclic at write time, and if
  cycles are written, it may cause issues at read time.
  
  A FileSet may be referenced by other resources in conjunction with
  Files. A File is preferred for something that can only be ever
  referenced by one resource, and a FileSet is preferred if it can be
  reference by multiple resources.
  
  
  Attributes:
      name:
          The format of this FileSet resource name must be:
          invocations/\ :math:`{INVOCATION_ID}/fileSets/`\
          {url_encode(FILE_SET_ID)}
      id:
          The resource ID components that identify the file set. They
          must match the resource name after proper encoding.
      file_sets:
          List of names of other file sets that are referenced from this
          one. Each name must point to a file set under the same
          invocation. The name format must be: invocations/\
          :math:`{INVOCATION_ID}/fileSets/`\ {FILE_SET_ID}
      files:
          Files that are contained within this file set. The uid field
          in the file should be unique for the Invocation.
  """,
  # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.FileSet)
  })
_sym_db.RegisterMessage(FileSet)
_sym_db.RegisterMessage(FileSet.Id)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
