version: "3.8"
services:
  envoy:
    build:
      context: ../resultstore-search-client/envoy/
      network: host
    image: gcr.io/google.com/gchips-productivity/resultstoresearch-envoy-test
    expose: 
      - "8080"
      - "9901"
    ports:
      - "8080:8080"
      - "9901:9901"  

  client:
    build:
      context: ../resultstore-search-client/
    image: gcr.io/google.com/gchips-productivity/resultstoresearch-client-test
    volumes:
      - ../resultstore-search-client/:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    ports:
      - "3000:80"
    expose:
      - "80"
    depends_on:
      - mock-server
      - envoy

  mock-server:
    build:
      context: ../resultstore-search-api/
      dockerfile: Dockerfile.test
    image: gcr.io/google.com/gchips-productivity/resultstoresearch-server-mock
    volumes:
      - ../resultstore-search-api/:/usr/src/app
    ports:
      - "9090:9090"

  # e2e:
  #   image: cypress
  #   build: ../e2e
  #   container_name: cypress
  #   network_mode: 'host'
  #   depends_on:
  #     - client
  #     - envoy
  #     - mock-server
  #   environment:
  #     - CYPRESS_baseUrl=http://localhost:3000/
  #     - CYPRESS_browser=chrome
  #   command: npx cypress run
  #   volumes:
  #     - ../e2e/cypress:/app/cypress
  #     - ../e2e/cypress.json:/app/cypress.json